<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableDynamicLoading>True</EnableDynamicLoading>
        <RootNamespace>SuperAutoIsland</RootNamespace>
        <Version>0.3.9.1</Version>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <Authors>lrs2187</Authors>
        <PackageVersion>0.3.9.1-dev.2</PackageVersion>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="ClassIsland.PluginSdk" Version="2.1.1.1">
            <ExcludeAssets>runtime; native</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="Jint" Version="4.16.1" />
        <ProjectReference Include="..\SuperAutoIsland.Interface\SuperAutoIsland.Interface.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets/icon.png" />
        <AvaloniaResource Include="Assets/sandrone.png" />
    </ItemGroup>
    
    <ItemGroup>
        <None Update="manifest.yml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="README.md">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="icon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        
        <Content Include="Assets/wwwroot/**/*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        
        <None Update="Assets\icon.png">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="Services\Automations\Blocks\Profile\" />
    </ItemGroup>
</Project>